# permissions for end users to edit devs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dev-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dev
    app.kubernetes.io/part-of: dev
    app.kubernetes.io/managed-by: kustomize
  name: dev-editor-role
rules:
- apiGroups:
  - api.gokula.dev
  resources:
  - devs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.gokula.dev
  resources:
  - devs/status
  verbs:
  - get
